// ABI codegen: read forge's compiled artifact and emit a committed TS `as const`
// ABI that the TS packages import (closes the hand-authored-ABI SPEC-GAP). The
// generated file IS the source of truth for viem bindings; regenerate whenever
// the .sol changes (`bun run build:contracts`). Committed so the JS gate
// (turbo typecheck / bun test) never needs forge.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = dirname(import.meta.dir); // packages/contracts
// (contract artifact name, exported const name, output module)
const TARGETS = [
  {
    artifact: "out/StakeSlash.sol/StakeSlash.json",
    constName: "stakeSlashAbi",
    out: "generated/stake-slash.abi.ts",
  },
] as const;

for (const t of TARGETS) {
  const artifactPath = join(ROOT, t.artifact);
  if (!existsSync(artifactPath)) {
    throw new Error(`Missing artifact ${t.artifact} — run \`forge build\` first.`);
  }
  const { abi } = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown[] };
  const outPath = join(ROOT, t.out);
  mkdirSync(dirname(outPath), { recursive: true });
  const banner =
    `// GENERATED by scripts/gen-abi.ts from ${t.artifact} — DO NOT EDIT.\n` +
    `// Regenerate with \`bun run build:contracts\` after changing the contract.\n`;
  writeFileSync(
    outPath,
    `${banner}export const ${t.constName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  console.log(`wrote ${t.out} (${abi.length} ABI entries)`);
}
