// Bundle @superjam/sdk into ONE self-contained ESM file vendored into every
// generated app. Generated apps deploy STANDALONE on Vercel, where the
// monorepo's `workspace:*` / `catalog:` protocols don't resolve — so the SDK
// (and its only dep chain: @superjam/shared/bridge + zod) must be inlined.
//
// generate.ts emits this artifact as `lib/superjam-sdk.js` + a tsconfig `paths`
// alias `@superjam/sdk` → it, so recipe/agent code keeps `import … from
// "@superjam/sdk"` unchanged. Re-run after the SDK changes: `bun run bundle:sdk`.
import { join } from "node:path";

const repoRoot = join(import.meta.dir, "..", "..", "..");
const entry = join(repoRoot, "packages/sdk/src/index.ts");
const outFile = join(import.meta.dir, "..", "vendor", "superjam-sdk.js");

const result = await Bun.build({
  entrypoints: [entry],
  target: "browser",
  format: "esm",
  minify: true, // self-contained runtime artifact — minified for upload size
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("SDK bundle failed");
}

const code = await result.outputs[0]!.text();
const banner =
  "// VENDORED @superjam/sdk — generated by apps/builder/scripts/bundle-sdk.ts.\n" +
  "// Do not edit by hand; re-run `bun run bundle:sdk` after the SDK changes.\n";
await Bun.write(outFile, banner + code);

console.log(`bundled @superjam/sdk → ${outFile} (${(banner.length + code.length) / 1024 | 0} KB)`);
